#!/bin/sh
### BEGIN INIT INFO
# Provides:             linknx
# Required-Start:       $remote_fs $syslog $time $network $eibd
# Required-Stop:        $remote_fs $syslog $time $network
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    linknx
### END INIT INFO

set -e
# /etc/init.d/linknx: start and stop the LINKNX daemon linknx

test -x /usr/local/bin/linknx || exit 0
umask 022

# User for linknx. It is recommended to not use "root".
# Best would be to create an own user with "useradd", but we will use the user pi
# here for simplicity.
LINKNX_USER=pi

# Config file
CONFIGFILE=/etc/linknx.xml

# PID file
PIDFILE=/var/run/linknx.pid

# Log file
LOGFILE=/var/log/linknx.log

if test -f /etc/default/linknx; then
    . /etc/default/linknx
fi

LINKNX_OPTS="-d --config=$CONFIGFILE --write=$CONFIGFILE --pid-file=$PIDFILE --daemon=$LOGFILE"

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting LINKNX daemon" "linknx" || true
    touch $LOGFILE $PIDFILE
    chown $LINKNX_USER $LOGFILE $PIDFILE
    if start-stop-daemon --start --chuid $LINKNX_USER --quiet --oknodo --exec /usr/local/bin/linknx -- $LINKNX_OPTS; then
	   log_end_msg 0 || true
	 else
	   log_end_msg 1 || true
	 fi
    ;;

  stop)
	 log_daemon_msg "Stopping LINKNX daemon" "linknx" || true
	 if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
	   log_end_msg 0 || true
	 else
	   log_end_msg 1 || true
	 fi
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  status)
	 status_of_proc /usr/local/bin/linknx linknx && exit 0 || exit $?
	 ;;

  *)
    log_action_msg "Usage: /etc/init.d/linknx {start|stop|restart|status}" || true
    exit 1
    ;;
esac

exit 0

